name: Stream Video to YouTube

on:
  workflow_dispatch:  # Allow manual triggering
  push:  # Automatically run on push to the repository
    branches:
      - main

jobs:
  stream-video:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y ffmpeg wget

    # Step 4: Run the streaming script
    - name: Run Streaming Script
      run: |
        python3 streaming_script.py
